pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
			sh '''
                    ls -la
                    node --version
                    npm --version
                    npm ci
                    npm run build
                    ls -l
                    pwd
                '''
              
            }
        }
		stage('test') {
		
		steps {
                sh '''
                    test -f build/index.html
                    npm test
                '''
            }
		
    }
}
post {
        always {
            junit 'test-results/junit.xml'
        }
    }
}